import { StyleSheet } from 'react-native';
import ResponsiveStyleSheet from '../utils/ResponsiveStyleSheet';
import { moderateScale, verticalScale, horizontalScale } from '../utils/ResponsiveUtils';

export const styles = ResponsiveStyleSheet.create({
    modalContainer: {
      flex: 1,
      backgroundColor: '#000000',
      paddingTop: 0,
    },
    modalContent: {
      flex: 1,
      backgroundColor: '#121212',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: moderateScale(20),
      paddingTop: verticalScale(30),
      marginTop: verticalScale(10),
      backgroundColor: '#1a1a1a',
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    title: {
      fontSize: moderateScale(20),
      fontWeight: 'bold',
      color: '#ffffff',
    },
    closeButton: {
      padding: moderateScale(8),
    },
    loaderContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      color: '#ffffff',
      marginTop: verticalScale(10),
      fontSize: moderateScale(16),
    },
    spacesList: {
      padding: moderateScale(15),
    },
    spaceItem: {
      backgroundColor: '#1a1a1a',
      borderRadius: moderateScale(12),
      marginBottom: verticalScale(15),
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#333',
    },
    spaceContent: {
      flexDirection: 'row',
      padding: moderateScale(15),
    },
    spaceImageContainer: {
      marginRight: horizontalScale(15),
      width: moderateScale(80),
      height: moderateScale(80),
      borderRadius: moderateScale(8),
      backgroundColor: '#333',
      overflow: 'hidden',
    },
    spaceThumb: {
      width: '100%',
      height: '100%',
    },
    spaceImagePlaceholder: {
      width: moderateScale(80),
      height: moderateScale(80),
      borderRadius: moderateScale(8),
      backgroundColor: '#333',
      justifyContent: 'center',
      alignItems: 'center',
    },
    spaceInfo: {
      flex: 1,
    },
    spaceName: {
      fontSize: moderateScale(18),
      fontWeight: 'bold',
      color: '#FFF',
      marginBottom: verticalScale(5),
    },
    spaceAddress: {
      fontSize: moderateScale(14),
      color: '#CCC',
      marginBottom: verticalScale(8),
    },
    tagsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    tag: {
      backgroundColor: '#444',
      borderRadius: moderateScale(12),
      paddingHorizontal: horizontalScale(8),
      paddingVertical: verticalScale(3),
      marginRight: horizontalScale(5),
      marginBottom: verticalScale(5),
    },
    tagText: {
      color: '#FFF',
      fontSize: moderateScale(12),
    },
    moreTag: {
      color: '#999',
      fontSize: moderateScale(12),
      marginLeft: horizontalScale(5),
      alignSelf: 'center',
    },
    spaceActions: {
      justifyContent: 'space-between',
      paddingLeft: horizontalScale(10),
    },
    favoriteButton: {
      width: moderateScale(40),
      height: moderateScale(40),
      borderRadius: moderateScale(20),
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: horizontalScale(10),
      // Añadir sombra para mejorar visibilidad
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: verticalScale(2),
      },
      shadowOpacity: 0.25,
      shadowRadius: moderateScale(3.84),
      elevation: 5,
    },
    favoriteButtonActive: {
      backgroundColor: 'rgba(255, 58, 94, 0.2)',
    },
    detailsButton: {
      padding: moderateScale(8),
      backgroundColor: 'rgba(74, 144, 226, 0.1)',
      borderRadius: moderateScale(20),
      width: moderateScale(40),
      height: moderateScale(40),
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: moderateScale(20),
    },
    emptyText: {
      color: '#ffffff',
      textAlign: 'center',
      fontSize: moderateScale(16),
      marginTop: verticalScale(10),
    },
    detailsContainer: {
      flex: 1,
      backgroundColor: '#121212',
      height: '100%',
      width: '100%',
    },
    detailsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: moderateScale(20),
      paddingTop: verticalScale(30),
      marginTop: verticalScale(10),
      backgroundColor: '#1a1a1a',
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    detailsTitle: {
      fontSize: moderateScale(20),
      fontWeight: 'bold',
      color: '#ffffff',
    },
    closeDetailsButton: {
      padding: moderateScale(8),
    },
    detailsScrollView: {
      flex: 1,
      padding: 0,
      backgroundColor: '#121212',
      height: '100%',
      width: '100%',
    },
    imagesScrollView: {
      height: verticalScale(200),
      marginBottom: verticalScale(20),
    },
    imageContainer: {
      position: 'relative',
      marginRight: horizontalScale(10),
    },
    imageOverlay: {
      position: 'absolute',
      top: verticalScale(10),
      left: horizontalScale(10),
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      paddingHorizontal: horizontalScale(8),
      paddingVertical: verticalScale(4),
      borderRadius: moderateScale(4),
      zIndex: 1,
    },
    imageOverlayText: {
      color: '#FFF',
      fontSize: moderateScale(12),
      fontWeight: 'bold',
    },
    spaceImage: {
      width: horizontalScale(300),
      height: verticalScale(200),
      borderRadius: moderateScale(12),
    },
    noImageContainer: {
      height: verticalScale(200),
      backgroundColor: '#1a1a1a',
      borderRadius: moderateScale(12),
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: verticalScale(20),
    },
    noImageText: {
      color: '#666',
      marginTop: verticalScale(10),
    },
    detailSection: {
      marginBottom: verticalScale(15),
      paddingHorizontal: horizontalScale(15),
      paddingVertical: verticalScale(10),
      borderBottomWidth: 0.5,
      borderBottomColor: '#333',
    },
    sectionTitle: {
      fontSize: moderateScale(18),
      fontWeight: 'bold',
      color: '#ffffff',
      marginBottom: verticalScale(10),
    },
    spaceName: {
      fontSize: moderateScale(24),
      fontWeight: 'bold',
      color: '#ffffff',
      marginBottom: verticalScale(5),
    },
    addressContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: verticalScale(5),
    },
    addressText: {
      fontSize: moderateScale(16),
      color: '#CCC',
      marginLeft: horizontalScale(8),
    },
    descriptionText: {
      fontSize: moderateScale(16),
      color: '#CCC',
      lineHeight: verticalScale(24),
    },
    capacityContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    capacityText: {
      fontSize: moderateScale(16),
      color: '#CCC',
      marginLeft: horizontalScale(8),
    },
    facilitiesContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    facilityTag: {
      backgroundColor: '#333',
      borderRadius: moderateScale(20),
      paddingHorizontal: horizontalScale(12),
      paddingVertical: verticalScale(6),
      marginRight: horizontalScale(8),
      marginBottom: verticalScale(8),
    },
    facilityText: {
      color: '#FFF',
      fontSize: moderateScale(14),
    },
    dayContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: verticalScale(10),
      paddingVertical: verticalScale(5),
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    dayName: {
      fontSize: moderateScale(16),
      color: '#FFF',
      fontWeight: 'bold',
      width: horizontalScale(100),
    },
    timeSlots: {
      flex: 1,
    },
    timeSlot: {
      fontSize: moderateScale(14),
      color: '#CCC',
      marginBottom: verticalScale(5),
    },
    closedText: {
      fontSize: moderateScale(14),
      color: '#FF3A5E',
      fontStyle: 'italic',
    },
    contactButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FF3A5E',
      borderRadius: moderateScale(25),
      paddingVertical: verticalScale(12),
      paddingHorizontal: horizontalScale(20),
      justifyContent: 'center',
      marginTop: verticalScale(15),
    },
    contactButtonText: {
      color: '#FFF',
      fontSize: moderateScale(16),
      marginLeft: horizontalScale(10),
    },
    socialContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    socialButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: verticalScale(8),
      paddingHorizontal: horizontalScale(12),
      borderRadius: moderateScale(8),
      marginRight: horizontalScale(10),
      marginBottom: verticalScale(10),
    },
    socialButtonText: {
      color: '#FFF',
      fontSize: moderateScale(14),
      marginLeft: horizontalScale(8),
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    bottomSpace: {
      height: verticalScale(10),
    },
  });