import { StyleSheet, Dimensions } from 'react-native';
import { moderateScale, verticalScale, horizontalScale } from '../utils/ResponsiveUtils';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#000000',
    },
    listContent: {
      padding: horizontalScale(16),
    },
    notificationItem: {
      backgroundColor: '#1E1E1E',
      borderRadius: moderateScale(12),
      marginBottom: verticalScale(12),
      overflow: 'hidden',
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: verticalScale(2) },
      shadowOpacity: 0.2,
      shadowRadius: moderateScale(4),
      borderWidth: 1,
      borderColor: '#2A2A2A',
      width: width * 0.9,
      alignSelf: 'center',
      maxWidth: 600,
    },
    readNotification: {
      backgroundColor: '#141414',
      opacity: 0.85,
      borderColor: '#1A1A1A',
    },
    notificationContent: {
      padding: moderateScale(12),
      width: '100%',
      alignSelf: 'center',
    },
    notificationHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: verticalScale(10),
      paddingHorizontal: horizontalScale(5),
      paddingVertical: verticalScale(5),
      width: '100%',
    },
    title: {
      fontSize: moderateScale(17),
      fontWeight: '600',
      color: '#E0E0E0',
      flex: 1,
      letterSpacing: 0.3,
      paddingRight: horizontalScale(10),
      textAlign: 'left',
    },
    readTitle: {
      color: '#808080',
      fontWeight: '500',
    },
    message: {
      fontSize: moderateScale(15),
      color: '#CCCCCC',
      marginBottom: verticalScale(16),
      lineHeight: moderateScale(22),
      letterSpacing: 0.2,
    },
    readMessage: {
      color: '#666666',
    },
    unreadDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#3B82F6',
      marginLeft: 8,
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 4,
    },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: verticalScale(12),
      gap: horizontalScale(8),
      flexWrap: 'wrap',
    },
    deleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: verticalScale(7),
      paddingHorizontal: horizontalScale(12),
      borderRadius: moderateScale(8),
      minWidth: horizontalScale(90),
      justifyContent: 'center',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: verticalScale(1) },
      shadowOpacity: 0.2,
      shadowRadius: moderateScale(2),
    },
    actionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: verticalScale(7),
      paddingHorizontal: horizontalScale(12),
      borderRadius: moderateScale(8),
      minWidth: horizontalScale(90),
      justifyContent: 'center',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: verticalScale(1) },
      shadowOpacity: 0.2,
      shadowRadius: moderateScale(2),
    },
    buttonText: {
      color: '#FFFFFF',
      fontSize: moderateScale(13.5),
      fontWeight: '600',
      marginLeft: horizontalScale(6),
      letterSpacing: 0.2,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: moderateScale(20),
      marginTop: verticalScale(50),
    },
    emptyText: {
      textAlign: 'center',
      color: '#808080',
      fontSize: moderateScale(16),
      marginTop: verticalScale(16),
      letterSpacing: 0.3,
    },
  });
  