import { StyleSheet } from 'react-native';
import { moderateScale, verticalScale, horizontalScale } from '../utils/ResponsiveUtils';

export 
const styles = StyleSheet.create({
  // Estilo para los enlaces
  linkText: {
    color: '#4287f5', // Color azul para los enlaces
    fontSize: moderateScale(12),
    textDecorationLine: 'underline',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: moderateScale(15),
  },
  modalContent: {
    backgroundColor: '#1E1E1E',
    borderRadius: moderateScale(15),
    padding: moderateScale(20),
    width: '100%',
    maxWidth: horizontalScale(500),
    maxHeight: '90%',
    borderLeftWidth: moderateScale(4),
    borderLeftColor: '#FF3A5E',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  closeButton: {
    padding: 5,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#FFFFFF',
  },
  requestItem: {
    backgroundColor: '#2A2A2A',
    borderRadius: moderateScale(10),
    padding: moderateScale(15),
    marginBottom: verticalScale(15),
    borderLeftWidth: moderateScale(3),
    borderLeftColor: '#FF3A5E',
  },
  categoryText: {
    color: '#FFFFFF',
    fontSize: moderateScale(14),
    fontWeight: 'bold',
  },
  dateText: {
    color: '#999999',
    fontSize: moderateScale(12),
    fontStyle: 'italic',
  },
  requestHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(10),
  },
  requestName: {
    fontSize: moderateScale(16),
    fontWeight: 'bold',
    color: '#FFFFFF',
    flex: 1,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: horizontalScale(10),
    paddingVertical: verticalScale(5),
    borderRadius: moderateScale(20),
    marginLeft: horizontalScale(10),
  },
  statusIcon: {
    marginRight: horizontalScale(5),
  },
  statusText: {
    color: '#FFFFFF',
    fontSize: moderateScale(12),
    fontWeight: 'bold',
  },
  requestDetails: {
    marginBottom: verticalScale(10),
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(5),
  },
  detailText: {
    marginLeft: horizontalScale(8),
    color: '#CCCCCC',
    fontSize: moderateScale(12), // Letra más pequeña
  },
  requestFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: moderateScale(1),
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
    paddingTop: verticalScale(10),
  },
  requestDate: {
    color: '#999999',
    fontSize: 12,
    fontStyle: 'italic',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 30,
  },
  emptyText: {
    color: '#FFFFFF',
    fontSize: 18,
    marginTop: 20,
    marginBottom: 10,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    marginTop: 5,
  },
  filterContainer: {
    marginBottom: 15,
  },
  filterLabel: {
    fontSize: 14,
    color: '#FFFFFF',
    marginBottom: 8,
    fontWeight: '500',
  },
  categoryFilterContainer: {
    paddingVertical: 5,
  },
  categoryFilterButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginRight: 8,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  categoryFilterButtonActive: {
    backgroundColor: 'rgba(255, 58, 94, 0.2)',
    borderColor: '#FF3A5E',
  },
  categoryFilterText: {
    color: '#CCCCCC',
    fontSize: 14,
  },
  categoryFilterTextActive: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  emptyFilterContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 30,
  },
  emptyFilterText: {
    fontSize: 16,
    color: '#999',
    textAlign: 'center',
    marginTop: 10,
  },
  detailsModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  detailsModalContent: {
    backgroundColor: '#1E1E1E',
    borderRadius: 15,
    width: '100%',
    maxHeight: '90%',
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 58, 94, 0.3)',
  },
  artistInfoContainer: {
    backgroundColor: '#2A2A2A',
    borderRadius: 10,
    padding: 15,
    marginTop: 5,
    overflow: 'hidden',
  },
  socialLinksContainer: {
    marginTop: 10,
  },
  socialLinksTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    marginBottom: 5,
  },
  socialLinks: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  socialLinkItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
    marginBottom: 5,
    backgroundColor: '#333',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
  },
  socialLinkText: {
    color: '#FFFFFF',
    marginLeft: 5,
    fontSize: 14,
  },
  detailsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 25,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    paddingBottom: 15,
  },
  detailsTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textShadowColor: 'rgba(255, 58, 94, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  statusSection: {
    alignItems: 'center',
    marginBottom: 25,
    paddingVertical: 15,
  },
  statusBadgeLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
  },
  statusTextLarge: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  rejectionReasonContainer: {
    marginTop: 15,
    padding: 15,
    backgroundColor: 'rgba(255, 58, 94, 0.1)',
    borderRadius: 10,
    width: '100%',
  },
  rejectionReasonLabel: {
    color: '#FF3A5E',
    fontWeight: 'bold',
    marginBottom: 5,
  },
  rejectionReasonText: {
    color: '#FFFFFF',
  },
  detailSection: {
    marginBottom: 20,
    padding: 15,
    backgroundColor: 'rgba(42, 42, 42, 0.8)',
    borderRadius: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#FF3A5E',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  detailSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FF3A5E',
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    paddingBottom: 8,
  },
  detailRow: {
    flexDirection: 'row',
    marginBottom: 8,
    flexWrap: 'wrap',
  },
  detailLabel: {
    color: '#FFFFFF',
    width: 120,
    fontSize: 15,
    fontWeight: 'bold',
  },
  detailValue: {
    color: '#DDDDDD',
    flex: 1,
    fontSize: moderateScale(12), // Letra más pequeña
    fontWeight: 'normal',
  },
  detailValueLink: {
    color: '#4287f5', // Color azul para los enlaces
    flex: 1,
    fontSize: moderateScale(12),
    fontWeight: 'normal',
    textDecorationLine: 'underline',
  },
  linkText: {
    color: '#4287f5', // Color azul para los enlaces
    textDecorationLine: 'underline',
    fontSize: moderateScale(12),
  },
  noSocialText: {
    color: '#999999',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: 10,
  },
  socialMediaContainer: {
    flexDirection: 'row',
    marginTop: 10,
    flexWrap: 'wrap',
  },
  socialMediaButton: {
    marginRight: 15,
    marginBottom: 10,
    padding: 12,
    backgroundColor: '#333333',
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  actionSection: {
    marginBottom: 20,
  },
  actionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 15,
  },
  approveButton: {
    backgroundColor: '#4CAF50',
    borderRadius: 30,
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 8,
  },
  rejectSection: {
    backgroundColor: '#2A2A2A',
    borderRadius: 10,
    padding: 15,
  },
  rejectLabel: {
    color: '#FFFFFF',
    marginBottom: 10,
  },
  rejectInput: {
    backgroundColor: '#333333',
    borderRadius: 8,
    padding: 12,
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(255, 58, 94, 0.3)',
    textAlignVertical: 'top',
    minHeight: 80,
    marginBottom: 15,
  },
  rejectButton: {
    backgroundColor: '#FF3A5E',
    borderRadius: 30,
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  socialMediaContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  socialMediaButton: {
    padding: 5,
    marginRight: 10,
  },
});
