import { StyleSheet, Dimensions } from 'react-native';
import { makeStylesResponsive, horizontalScale, verticalScale, moderateScale, adaptiveFontSize } from '../utils/ResponsiveUtils';

// Definimos los estilos base
const baseStyles = {
    container: {
      flex: 1,
      backgroundColor: '#121212',
    },
    mapAccessButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#FF3A5E',
      padding: moderateScale(15),
      marginHorizontal: horizontalScale(15),
      marginVertical: verticalScale(10),
      borderRadius: moderateScale(10),
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: verticalScale(2) },
      shadowOpacity: 0.3,
      shadowRadius: moderateScale(3),
    },
    mapAccessButtonText: {
      color: '#FFFFFF',
      fontSize: adaptiveFontSize(16),
      fontWeight: 'bold',
      flex: 1,
      textAlign: 'center',
    },
    fullScreenContainer: {
      flex: 1,
      backgroundColor: '#121212',
    },
    fullScreenHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: moderateScale(15),
      backgroundColor: '#1E1E1E',
      borderBottomWidth: moderateScale(1),
      borderBottomColor: '#333',
    },
    fullScreenSearchContainer: {
      backgroundColor: 'transparent',
      borderRadius: moderateScale(20),
      marginHorizontal: horizontalScale(15),
      marginVertical: verticalScale(10),
      paddingHorizontal: 0,
      paddingVertical: 0,
      zIndex: 10,
    },
    fullScreenSearchInput: {
      flex: 1,
      color: '#FFF',
      fontSize: 16,
      padding: 8,
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 5,
    },
    backButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      marginLeft: 5,
    },
    fullScreenTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#FFFFFF',
      flex: 1,
      textAlign: 'center',
    },
    fullScreenMapContainer: {
      flex: 1,
      width: '100%',
      height: '100%',
    },
    fullScreenMap: {
      width: '100%',
      height: '100%',
    },
    calloutContainer: {
      width: 200,
      padding: 10,
    },
    calloutTitle: {
      fontWeight: 'bold',
      fontSize: 14,
      color: '#000',
      marginBottom: 5,
    },
    calloutAddress: {
      fontSize: 12,
      color: '#555',
      marginBottom: 5,
    },
    calloutDistance: {
      fontSize: 12,
      color: '#FF3A5E',
      marginBottom: 5,
    },
    calloutAction: {
      fontSize: 12,
      color: '#4285F4',
      fontStyle: 'italic',
    },
    mapContainerMain: {
      width: '100%',
      height: 350,
      borderRadius: 0,
      overflow: 'hidden',
      marginBottom: 5,
      borderBottomWidth: 2,
      borderBottomColor: '#FF3A5E',
    },
    loadingWebView: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(30, 30, 30, 0.8)',
    },
    loadingWebViewText: {
      marginTop: 10,
      color: '#FFFFFF',
      fontSize: 16,
    },
    mapControlsMain: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: 5,
      paddingHorizontal: 15,
      backgroundColor: '#1E1E1E',
      paddingVertical: verticalScale(8),
      borderBottomWidth: moderateScale(1),
      borderBottomColor: '#333',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: moderateScale(15),
      borderBottomWidth: moderateScale(1),
      borderBottomColor: '#333',
    },
    headerLeft: {
      width: horizontalScale(40),
      alignItems: 'flex-start',
      marginTop: verticalScale(-5),
      backgroundColor: 'transparent',
    },
    headerRight: {
      width: horizontalScale(40),
      alignItems: 'flex-end',
    },
    locationButton: {
      padding: moderateScale(5),
    },
    title: {
      fontSize: adaptiveFontSize(20),
      fontWeight: 'bold',
      color: '#FFFFFF',
      flex: 1,
      textAlign: 'center',
    },
    closeButton: {
      padding: moderateScale(5),
      marginTop: verticalScale(-5),
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#1E1E1E',
      margin: moderateScale(15),
      borderRadius: 10,
      paddingHorizontal: 10,
    },
    searchIcon: {
      marginRight: 10,
    },
    searchInput: {
      flex: 1,
      height: 40,
      color: '#FFFFFF',
      fontSize: 16,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 10,
      color: '#FFFFFF',
      fontSize: 16,
    },
    listContent: {
      padding: 15,
    },
    spaceItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: '#1E1E1E',
      borderRadius: 10,
      padding: 15,
      marginBottom: 15,
      borderLeftWidth: 3,
      borderLeftColor: '#FF3A5E',
    },
    spaceContent: {
      flex: 1,
    },
    spaceName: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#FFFFFF',
      marginBottom: 5,
    },
    spaceAddress: {
      fontSize: 14,
      color: '#AAA',
      marginBottom: 5,
    },
    spaceCapacity: {
      fontSize: 14,
      color: '#FF3A5E',
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    emptyText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#FFFFFF',
      marginTop: 15,
    },
    emptySubText: {
      fontSize: 14,
      color: '#AAA',
      marginTop: 5,
    },
    modalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 15,
    },
    modalContent: {
      backgroundColor: '#1E1E1E',
      borderRadius: 15,
      padding: 20,
      width: '100%',
      maxWidth: 400,
      height: '90%',
      maxHeight: 600,
      position: 'relative',
      borderLeftWidth: 4,
      borderLeftColor: '#FF3A5E',
      flex: 1,
      flexDirection: 'column',
    },
    modalScrollContent: {
      paddingBottom: 100,
      flexGrow: 1,
    },
    modalScrollView: {
      flex: 1,
      width: '100%',
    },
    closeButton: {
      position: 'absolute',
      top: 10,
      right: 10,
      zIndex: 10,
      backgroundColor: 'rgba(30, 30, 30, 0.7)',
      borderRadius: 15,
      padding: 5,
    },
    spacePlaceholder: {
      width: '100%',
      height: verticalScale(180),
      borderRadius: moderateScale(10),
      overflow: 'hidden',
      marginBottom: verticalScale(15),
      marginTop: verticalScale(30),
      backgroundColor: '#1E1E1E',
    },
    imageContainer: {
      width: '100%',
      height: '100%',
      borderRadius: moderateScale(10),
      overflow: 'hidden',
    },
    spaceImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    imageScrollView: {
      width: '100%',
      height: '100%',
    },
    imageScrollContent: {
      alignItems: 'center',
    },
    imageItem: {
      width: horizontalScale(220),
      height: '100%',
      borderRadius: moderateScale(10),
      marginRight: horizontalScale(10),
      overflow: 'hidden',
    },
    placeholderContainer: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    placeholderImageContainer: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(30, 30, 30, 0.7)',
      borderRadius: moderateScale(10),
    },
    placeholderText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: 'bold',
      marginTop: 10,
      textAlign: 'center',
      paddingHorizontal: 10,
    },
    modalSpaceName: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#FFFFFF',
      marginTop: 10,
      marginBottom: 5,
      textAlign: 'left',
    },
    modalSpaceAddress: {
      fontSize: 16,
      color: '#CCCCCC',
      marginBottom: 15,
      textAlign: 'left',
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
      width: '100%',
    },
    infoText: {
      fontSize: adaptiveFontSize(14),
      color: '#FFFFFF',
      marginLeft: horizontalScale(10),
      flex: 1,
    },
    infoSection: {
      marginTop: verticalScale(15),
      marginBottom: verticalScale(10),
      width: '100%',
    },
    sectionTitle: {
      fontSize: adaptiveFontSize(16),
      fontWeight: 'bold',
      color: '#FFFFFF',
      marginBottom: verticalScale(10),
      marginTop: verticalScale(15),
    },
    tagsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: verticalScale(10),
    },
    tagItem: {
      backgroundColor: 'rgba(255, 58, 94, 0.1)',
      borderRadius: moderateScale(15),
      paddingHorizontal: horizontalScale(12),
      paddingVertical: verticalScale(6),
      marginRight: horizontalScale(8),
      marginBottom: verticalScale(8),
      borderWidth: moderateScale(1),
      borderColor: 'rgba(255, 58, 94, 0.3)',
    },
    tagText: {
      color: '#FFFFFF',
      fontSize: adaptiveFontSize(12),
    },
    horariosContainer: {
      backgroundColor: 'rgba(255, 58, 94, 0.1)',
      borderRadius: 12,
      padding: 10,
      marginTop: 8,
      marginBottom: 15,
      width: '100%',
      borderWidth: 1,
      borderColor: 'rgba(255, 58, 94, 0.2)',
    },
    horarioItem: {
      flexDirection: 'row',
      marginBottom: 8,
      paddingVertical: 4,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255, 255, 255, 0.05)',
      justifyContent: 'space-between',
      width: '100%',
      paddingHorizontal: 2,
    },
    horarioDia: {
      color: '#FFFFFF',
      fontWeight: 'bold',
      width: 95,
      fontSize: 14,
    },
    horarioHoras: {
      color: '#FFFFFF',
      fontSize: 14,
      textAlign: 'right',
      flex: 1,
      paddingLeft: 5,
    },
    descriptionTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#FFFFFF',
      marginTop: 15,
      marginBottom: 10,
    },
    descriptionText: {
      fontSize: 14,
      color: '#FFFFFF',
      lineHeight: 20,
      backgroundColor: 'rgba(255, 58, 94, 0.1)',
      padding: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'rgba(255, 58, 94, 0.2)',
    },
    requestButton: {
      backgroundColor: '#FF3A5E',
      borderRadius: 25,
      paddingVertical: 15,
      paddingHorizontal: 20,
      alignItems: 'center',
      marginTop: 30,
      marginBottom: 30,
      width: '100%',
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
    },
    requestButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
    mapModalContent: {
      backgroundColor: '#1E1E1E',
      borderRadius: 15,
      padding: 20,
      width: '100%',
      maxWidth: 600,
      maxHeight: '90%',
      position: 'relative',
      borderLeftWidth: 4,
      borderLeftColor: '#FF3A5E',
    },
    mapTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#FFFFFF',
      marginBottom: 10,
      marginTop: 30,
      textAlign: 'center',
    },
    mapControls: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: 15,
      paddingHorizontal: 10,
    },
    mapControlButton: {
      backgroundColor: '#2A2A2A',
      borderRadius: 8,
      padding: 8,
      alignItems: 'center',
      justifyContent: 'center',
      width: '30%',
      flexDirection: 'row',
    },
    mapControlButtonActive: {
      backgroundColor: '#3A3A3A',
      borderLeftWidth: 2,
      borderLeftColor: '#FF3A5E',
    },
    mapControlText: {
      color: '#FFFFFF',
      fontSize: 12,
      marginLeft: 5,
    },
    mapContainer: {
      width: '100%',
      height: 300,
      borderRadius: 10,
      overflow: 'hidden',
      marginBottom: 15,
    },
    mapPlaceholder: {
      width: '100%',
      height: '100%',
      backgroundColor: '#2A2A2A',
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    mapPlaceholderText: {
      color: '#FFFFFF',
      fontSize: 16,
      textAlign: 'center',
      marginTop: 10,
      marginBottom: 20,
    },
    openMapsButton: {
      backgroundColor: '#FF3A5E',
      borderRadius: 10,
      padding: 12,
      alignItems: 'center',
      justifyContent: 'center',
      width: '80%',
    },
    openMapsButtonText: {
      color: '#FFFFFF',
      fontWeight: 'bold',
      fontSize: 16,
    },
    nearbyTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#FFFFFF',
      marginBottom: 10,
      marginTop: 10,
    },
    nearbyList: {
      maxHeight: 200,
    },
    nearbyListContent: {
      paddingBottom: 10,
    },
    nearbyItem: {
      backgroundColor: '#2A2A2A',
      borderRadius: 10,
      padding: 15,
      marginBottom: 10,
      borderLeftWidth: 3,
      borderLeftColor: '#FF3A5E',
    },
    nearbyName: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#FFFFFF',
      marginBottom: 5,
    },
    nearbyAddress: {
      fontSize: 14,
      color: '#AAA',
      marginBottom: 5,
    },
    nearbyDistance: {
      fontSize: 14,
      color: '#FF3A5E',
    },
    emptyNearby: {
      padding: 20,
      alignItems: 'center',
    },
    emptyNearbyText: {
      fontSize: 16,
      color: '#AAA',
      textAlign: 'center',
    },
    viewLocationButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FF3A5E',
      borderRadius: 10,
      padding: 12,
      marginTop: 15,
      marginBottom: 10,
    },
    viewLocationButtonText: {
      color: '#FFFFFF',
      fontWeight: 'bold',
      fontSize: 16,
      marginLeft: 8,
    },
  };

// Convertimos los estilos base en estilos responsivos
export const styles = StyleSheet.create(makeStylesResponsive(baseStyles));