import { StyleSheet } from 'react-native';
import { moderateScale, verticalScale, horizontalScale } from '../utils/ResponsiveUtils';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
    padding: moderateScale(16),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(16),
    borderBottomWidth: moderateScale(1),
    borderBottomColor: '#FF3A5E',
    paddingBottom: verticalScale(10),
  },
  title: {
    fontSize: moderateScale(18),
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF3A5E',
    paddingHorizontal: horizontalScale(12),
    paddingVertical: verticalScale(8),
    borderRadius: moderateScale(6),
  },
  refreshButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    marginLeft: horizontalScale(6),
    fontSize: moderateScale(14),
  },
  loadingText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    marginTop: verticalScale(10),
    fontSize: moderateScale(16),
  },
  refreshingIndicator: {
    backgroundColor: 'rgba(255, 58, 94, 0.2)',
    padding: moderateScale(10),
    borderRadius: moderateScale(8),
    marginBottom: verticalScale(10),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: moderateScale(1),
    borderColor: 'rgba(255, 58, 94, 0.5)',
  },
  refreshingText: {
    marginLeft: horizontalScale(10),
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: moderateScale(14),
  },
  card: {
    backgroundColor: '#1a1a1a',
    borderRadius: moderateScale(12),
    borderWidth: moderateScale(1),
    borderColor: '#FF3A5E',
    padding: moderateScale(16),
    marginBottom: verticalScale(16),
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: verticalScale(2) },
    shadowOpacity: 0.1,
    shadowRadius: moderateScale(4),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'nowrap',
  },
  userInfo: {
    flex: 1,
    flexShrink: 1,
    overflow: 'hidden',
  },
  userName: {
    fontSize: moderateScale(16),
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: verticalScale(4),
    flexShrink: 1,
  },
  userEmail: {
    fontSize: moderateScale(14),
    color: '#CCCCCC',
    marginBottom: verticalScale(4),
    flexShrink: 1,
    flexWrap: 'nowrap',
  },
  userRole: {
    fontSize: moderateScale(14),
    color: '#FFFFFF',
    paddingHorizontal: horizontalScale(8),
    paddingVertical: verticalScale(4),
    borderRadius: moderateScale(10),
    alignSelf: 'flex-start',
    marginTop: verticalScale(8),
    fontWeight: 'bold',
  },
  userActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
    marginLeft: horizontalScale(8),
  },
  actionButton: {
    padding: moderateScale(8),
    borderRadius: moderateScale(6),
    marginLeft: horizontalScale(8),
    width: moderateScale(36),
    height: moderateScale(36),
    justifyContent: 'center',
    alignItems: 'center',
  },
  editButton: {
    backgroundColor: '#FF3A5E',
  },
  deleteButton: {
    backgroundColor: '#f44336',
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000000',
    padding: moderateScale(20),
  },
  errorText: {
    color: '#ff4757',
    textAlign: 'center',
    marginTop: verticalScale(10),
    fontSize: moderateScale(16),
    padding: moderateScale(10),
  },
  emptyText: {
    textAlign: 'center',
    fontSize: moderateScale(16),
    color: '#FFFFFF',
    marginTop: verticalScale(20),
    backgroundColor: 'rgba(255, 58, 94, 0.1)',
    padding: moderateScale(15),
    borderRadius: moderateScale(8),
    borderWidth: moderateScale(1),
    borderColor: 'rgba(255, 58, 94, 0.3)',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    padding: moderateScale(20),
  },
  modalContent: {
    backgroundColor: '#1a1a1a',
    borderRadius: moderateScale(12),
    borderWidth: moderateScale(1),
    borderColor: '#FF3A5E',
    padding: moderateScale(20),
    width: '90%',
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: moderateScale(20),
    fontWeight: 'bold',
    marginBottom: verticalScale(16),
    textAlign: 'center',
    color: '#FFFFFF',
  },
  inputLabel: {
    fontSize: moderateScale(16),
    marginBottom: verticalScale(8),
    color: '#FFFFFF',
  },
  infoText: {
    fontSize: moderateScale(16),
    marginBottom: verticalScale(15),
    padding: moderateScale(10),
    backgroundColor: '#2a2a2a',
    borderRadius: moderateScale(5),
    color: '#FFFFFF',
    borderWidth: moderateScale(1),
    borderColor: '#333333',
  },
  roleSelector: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: verticalScale(20),
  },
  roleOption: {
    padding: moderateScale(10),
    borderRadius: moderateScale(5),
    borderWidth: moderateScale(1),
    borderColor: '#333333',
    marginRight: horizontalScale(8),
    marginBottom: verticalScale(8),
    minWidth: horizontalScale(70),
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
  },
  selectedRole: {
    backgroundColor: '#FF3A5E',
    borderColor: '#FF3A5E',
  },
  roleText: {
    color: '#FFFFFF',
    fontSize: moderateScale(14),
  },
  selectedRoleText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: moderateScale(14),
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: verticalScale(20),
    gap: horizontalScale(10),
  },
  modalButton: {
    padding: moderateScale(12),
    borderRadius: moderateScale(6),
    minWidth: horizontalScale(100),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  cancelButton: {
    backgroundColor: '#757575',
  },
  saveButton: {
    backgroundColor: '#4CAF50',
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: verticalScale(8),
    paddingHorizontal: horizontalScale(12),
    borderRadius: moderateScale(6),
    minWidth: horizontalScale(100),
    justifyContent: 'center',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: moderateScale(14),
    fontWeight: '600',
    marginLeft: horizontalScale(4),
  },
});
