import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#000',
      paddingHorizontal: 20,
      paddingTop: 40, // Añadir espacio en la parte superior para que no llegue a la barra de estado
      paddingBottom: 20,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#2C3E50',
    },
    imageGallery: {
      height: 200,
      marginBottom: 20,
    },
    spaceImage: {
      width: 300,
      height: 200,
      borderRadius: 10,
      marginRight: 10,
    },
    section: {
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#2C3E50',
      marginBottom: 10,
    },
    text: {
      fontSize: 16,
      color: '#34495E',
      lineHeight: 24,
    },
    facilitiesContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    facilityTag: {
      backgroundColor: '#F0F7FF',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 15,
      marginRight: 8,
      marginBottom: 8,
    },
    facilityTagEditable: {
      backgroundColor: '#F0F7FF',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 15,
      marginRight: 8,
      marginBottom: 8,
      flexDirection: 'row',
      alignItems: 'center',
    },
    facilityText: {
      color: '#4A90E2',
      fontSize: 14,
      marginRight: 5,
    },
    facilitiesInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    facilitiesInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: '#E0E0E0',
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      color: '#2C3E50',
      marginRight: 10,
    },
    addFacilityButton: {
      backgroundColor: '#FF3A5E',
      width: 44,
      height: 44,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
    },
    facilitiesTagsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: 15,
    },
    scheduleItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
    },
    dayText: {
      fontSize: 16,
      color: '#2C3E50',
      fontWeight: '500',
    },
    timeText: {
      fontSize: 16,
      color: '#7F8C8D',
    },
    contactCard: {
      backgroundColor: '#000000',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#ffffff',
      padding: 16,
      marginTop: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    contactRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
    },
    contactIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#FFF0F3',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    contactTextContainer: {
      flex: 1,
    },
    contactLabel: {
      fontSize: 14,
      color: '#7F8C8D',
      marginBottom: 4,
    },
    contactValue: {
      fontSize: 16,
      color: '#2C3E50',
      fontWeight: '500',
    },
    contactDivider: {
      height: 1,
      backgroundColor: '#F0F0F0',
      marginVertical: 12,
    },
    socialCardContainer: {
      backgroundColor: '#000000',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#ffffff',
      padding: 16,
      marginTop: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    socialScrollContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
    },
    socialButton: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: '#F8F9FA',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 1,
    },
    noSocialText: {
      fontSize: 16,
      color: '#7F8C8D',
      fontStyle: 'italic',
      marginTop: 8,
    },
    editButton: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: 'rgb(255, 255, 255)',
    },
    editButtonText: {
      marginLeft: 2,
      color: '#000000',
      fontWeight: 'bold',
    },
    saveButton: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#FF3A5E',
    },
    saveButtonText: {
      marginLeft: 5,
      color: '#FFF',
      fontWeight: 'bold',
    },
    inputGroup: {
      marginBottom: 20,
    },
    label: {
      fontSize: 16,
      color: '#2C3E50',
      marginBottom: 8,
    },
    input: {
      borderWidth: 1,
      borderColor: '#E0E0E0',
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      color: '#2C3E50',
    },
    contactContainer: {
      marginBottom: 10,
    },
    contactField: {
      marginBottom: 12,
    },
    contactLabel: {
      fontSize: 14,
      color: '#7F8C8D',
      marginBottom: 5,
    },
    socialContainer: {
      marginBottom: 10,
    },
    socialField: {
      marginBottom: 12,
    },
    socialLabel: {
      fontSize: 14,
      color: '#7F8C8D',
      marginBottom: 5,
    },
    textArea: {
      height: 100,
      textAlignVertical: 'top',
    },
    imagePickerButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 15,
      borderWidth: 2,
      borderStyle: 'dashed',
      borderColor: '#4A90E2',
      borderRadius: 10,
      marginBottom: 10,
    },
    imagePickerText: {
      marginLeft: 10,
      fontSize: 16,
      color: '#4A90E2',
    },
    imagePreviewContainer: {
      flexDirection: 'row',
      marginBottom: 20,
    },
    imagePreview: {
      marginRight: 10,
      position: 'relative',
    },
    previewImage: {
      width: 100,
      height: 100,
      borderRadius: 8,
    },
    removeImageButton: {
      position: 'absolute',
      top: -10,
      right: -10,
      backgroundColor: '#FFF',
      borderRadius: 12,
    },
    dayContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
      paddingRight: 10,
      width: '100%',
    },
    toggleButton: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 15,
      marginLeft: 10,
    },
    toggleActive: {
      backgroundColor: '#FF3A5E',
    },
    toggleInactive: {
      backgroundColor: '#34495E',
    },
    toggleText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: 'bold',
    },
    timeSlotContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
      paddingLeft: 20,
    },
    addSlotButton: {
      marginLeft: 10,
      padding: 5,
    },
    removeSlotButton: {
      marginLeft: 10,
      padding: 5,
    },
    scheduleInputContainer: {
      marginBottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: '#E0E0E0',
      paddingBottom: 10,
    },
    timePickerButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: '#E0E0E0',
      borderRadius: 8,
      padding: 10,
      width: 100,
      backgroundColor: '#F8F9FA',
    },
    timePickerButtonText: {
      fontSize: 16,
      color: '#2C3E50',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'flex-end',
    },
    timePickerModal: {
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 20,
      maxHeight: '70%',
    },
    timePickerHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#E0E0E0',
    },
    timePickerTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#2C3E50',
    },
    timeList: {
      maxHeight: 300,
    },
    timeItem: {
      paddingVertical: 15,
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderBottomColor: '#F0F0F0',
    },
    timeItemText: {
      fontSize: 18,
      color: '#2C3E50',
    },
    backButton: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#2C3E50',
      marginLeft: 10,
    },
    detailsContainer: {
      backgroundColor: '#000000',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#ffffff',
      padding: 16,
      marginVertical: 8,
    },
    detailRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    descriptionContainer: {
      marginTop: 10,
      paddingTop: 10,
      borderTopWidth: 0.5,
      borderTopColor: '#555555',
    },
  });
  