import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    modalContainer: {
      flex: 1,
      backgroundColor: '#000000',
      paddingTop: 0,
    },
    modalContent: {
      flex: 1,
      backgroundColor: '#121212',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      paddingTop: 30,
      marginTop: 10,
      backgroundColor: '#1a1a1a',
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    title: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#ffffff',
    },
    closeButton: {
      padding: 8,
    },
    loaderContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      color: '#ffffff',
      marginTop: 10,
      fontSize: 16,
    },
    spacesList: {
      padding: 15,
    },
    spaceItem: {
      backgroundColor: '#1a1a1a',
      borderRadius: 12,
      marginBottom: 15,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#333',
    },
    spaceContent: {
      flexDirection: 'row',
      padding: 15,
    },
    spaceImageContainer: {
      marginRight: 15,
      width: 80,
      height: 80,
      borderRadius: 8,
      backgroundColor: '#333',
      overflow: 'hidden',
    },
    spaceThumb: {
      width: '100%',
      height: '100%',
    },
    spaceImagePlaceholder: {
      width: 80,
      height: 80,
      borderRadius: 8,
      backgroundColor: '#333',
      justifyContent: 'center',
      alignItems: 'center',
    },
    spaceInfo: {
      flex: 1,
    },
    spaceName: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#FFF',
      marginBottom: 5,
    },
    spaceAddress: {
      fontSize: 14,
      color: '#CCC',
      marginBottom: 8,
    },
    tagsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    tag: {
      backgroundColor: '#444',
      borderRadius: 12,
      paddingHorizontal: 8,
      paddingVertical: 3,
      marginRight: 5,
      marginBottom: 5,
    },
    tagText: {
      color: '#FFF',
      fontSize: 12,
    },
    moreTag: {
      color: '#999',
      fontSize: 12,
      marginLeft: 5,
      alignSelf: 'center',
    },
    spaceActions: {
      justifyContent: 'space-between',
      paddingLeft: 10,
    },
    favoriteButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
      // Añadir sombra para mejorar visibilidad
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    favoriteButtonActive: {
      backgroundColor: 'rgba(255, 58, 94, 0.2)',
    },
    detailsButton: {
      padding: 8,
      backgroundColor: 'rgba(74, 144, 226, 0.1)',
      borderRadius: 20,
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    emptyText: {
      color: '#ffffff',
      textAlign: 'center',
      fontSize: 16,
      marginTop: 10,
    },
    detailsContainer: {
      flex: 1,
      backgroundColor: '#121212',
      height: '100%',
      width: '100%',
    },
    detailsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      paddingTop: 30,
      marginTop: 10,
      backgroundColor: '#1a1a1a',
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    detailsTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#ffffff',
    },
    closeDetailsButton: {
      padding: 8,
    },
    detailsScrollView: {
      flex: 1,
      padding: 0,
      backgroundColor: '#121212',
      height: '100%',
      width: '100%',
    },
    imagesScrollView: {
      height: 200,
      marginBottom: 20,
    },
    imageContainer: {
      position: 'relative',
      marginRight: 10,
    },
    imageOverlay: {
      position: 'absolute',
      top: 10,
      left: 10,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 4,
      zIndex: 1,
    },
    imageOverlayText: {
      color: '#FFF',
      fontSize: 12,
      fontWeight: 'bold',
    },
    spaceImage: {
      width: 300,
      height: 200,
      borderRadius: 12,
    },
    noImageContainer: {
      height: 200,
      backgroundColor: '#1a1a1a',
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    noImageText: {
      color: '#666',
      marginTop: 10,
    },
    detailSection: {
      marginBottom: 15,
      paddingHorizontal: 15,
      paddingVertical: 10,
      borderBottomWidth: 0.5,
      borderBottomColor: '#333',
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#ffffff',
      marginBottom: 10,
    },
    spaceName: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#ffffff',
      marginBottom: 5,
    },
    addressContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 5,
    },
    addressText: {
      fontSize: 16,
      color: '#CCC',
      marginLeft: 8,
    },
    descriptionText: {
      fontSize: 16,
      color: '#CCC',
      lineHeight: 24,
    },
    capacityContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    capacityText: {
      fontSize: 16,
      color: '#CCC',
      marginLeft: 8,
    },
    facilitiesContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    facilityTag: {
      backgroundColor: '#333',
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 6,
      marginRight: 8,
      marginBottom: 8,
    },
    facilityText: {
      color: '#FFF',
      fontSize: 14,
    },
    dayContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
      paddingVertical: 5,
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    dayName: {
      fontSize: 16,
      color: '#FFF',
      fontWeight: 'bold',
      width: 100,
    },
    timeSlots: {
      flex: 1,
    },
    timeSlot: {
      fontSize: 14,
      color: '#CCC',
      textAlign: 'right',
    },
    closedText: {
      fontSize: 14,
      color: '#FF3A5E',
      fontStyle: 'italic',
    },
    contactButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#4A90E2',
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderRadius: 8,
      marginBottom: 10,
    },
    contactButtonText: {
      color: '#FFF',
      fontSize: 16,
      marginLeft: 10,
    },
    socialContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    socialButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
      marginRight: 10,
      marginBottom: 10,
    },
    socialButtonText: {
      color: '#FFF',
      fontSize: 14,
      marginLeft: 8,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    bottomSpace: {
      height: 10,
    },
  });