import { StyleSheet, Platform, StatusBar, Dimensions } from 'react-native';
import { moderateScale, verticalScale, horizontalScale } from '../utils/ResponsiveUtils';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#000000',
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: {
      flex: 1,
      backgroundColor: '#121212',
      padding: moderateScale(15),
      paddingTop: verticalScale(35), // Margen para respetar la barra de estado
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      backgroundColor: '#1a1a1a',
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    modalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.95)',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 9999,
      paddingTop: 35, // Margen para respetar la barra de estado
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      backgroundColor: '#1a1a1a',
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '80%',
    },
    closeButton: {
      padding: moderateScale(5),
      position: 'absolute',
      right: horizontalScale(10),
      top: '50%',
      transform: [{ translateY: -12 }],
      zIndex: 999,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#ffffff',
      marginRight: 10,
    },
    notificationBadge: {
      backgroundColor: '#FF3A5E',
      borderRadius: 15,
      minWidth: 30,
      height: 30,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 8,
      marginLeft: 10,
      borderWidth: 2,
      borderColor: '#FFFFFF',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 5,
    },
    notificationCount: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
    closeButton: {
      padding: 8,
    },
    notificationsList: {
      flex: 1,
    },
    noNotificationsText: {
      color: '#ffffff',
      textAlign: 'center',
      fontSize: 16,
      marginTop: 20,
    },
    container: {
      flex: 1,
      backgroundColor: '#000000',
    },
    header: {
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight + verticalScale(10) : verticalScale(50), // Ajustado dinámicamente para respetar la barra de estado
      paddingHorizontal: horizontalScale(20),
      paddingBottom: verticalScale(15),
      backgroundColor: '#000000',
      borderBottomLeftRadius: moderateScale(30),
      borderBottomRightRadius: moderateScale(30),
      marginBottom: verticalScale(20),
    },
    welcomeContainer: {
      marginRight: horizontalScale(50),
    },
    welcome: {
      fontSize: moderateScale(24),
      color: '#ffffff',
      fontWeight: '300',
    },
    userName: {
      fontSize: moderateScale(32),
      color: '#ffffff',
      fontWeight: 'bold',
    },
    headerButton: {
      position: 'absolute',
      right: horizontalScale(20),
      top: Platform.OS === 'android' ? StatusBar.currentHeight + verticalScale(10) : verticalScale(50), // Ajustado dinámicamente para alinearse con el header
      backgroundColor: '#ff4757',
      paddingHorizontal: horizontalScale(7),
      paddingVertical: verticalScale(8),
      borderRadius: moderateScale(18),
    },
    headerButtonText: {
      color: '#ffffff',
      fontSize: moderateScale(11.5),
      fontWeight: '600',
    },
    notification: {
      backgroundColor: '#1a1a1a',
      borderRadius: moderateScale(12),
      padding: moderateScale(16),
      marginHorizontal: horizontalScale(20),
      marginBottom: verticalScale(10),
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: verticalScale(2) },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    notificationText: {
      fontSize: moderateScale(16),
      color: '#ffffff',
      marginBottom: verticalScale(10),
    },
    notificationActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: horizontalScale(10),
    },
    notificationButtonText: {
      color: '#ffffff',
      fontSize: moderateScale(14),
      fontWeight: 'bold',
    },
    artistButtonText: {
      color: '#FFFFFF',
      fontSize: moderateScale(16),
      fontWeight: 'bold',
    },
    profileButtonsContainer: {
      marginTop: verticalScale(16),
      marginBottom: verticalScale(24),
      paddingHorizontal: horizontalScale(20),
    },
    profileSection: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: verticalScale(12),
      width: '100%',
    },
    profileButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#865FF4',
      paddingVertical: verticalScale(12),
      paddingHorizontal: horizontalScale(16),
      borderRadius: moderateScale(20),
    },
    managerButton: {
      backgroundColor: '#00EA01',
      borderRadius: moderateScale(20),
    },
    deleteButton: {
      backgroundColor: '#E74C3C',
      paddingVertical: verticalScale(12),
      paddingHorizontal: horizontalScale(12),
      borderRadius: moderateScale(20),
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: horizontalScale(10),
      width: horizontalScale(45),
    },
    deleteManagerButton: {
      backgroundColor: '#C0392B',
    },
    profileButtonText: {
      color: '#FFFFFF',
      fontSize: moderateScale(15),
      fontWeight: '600',
      marginLeft: horizontalScale(10),
      textShadowColor: '#000000',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 1,
    },
    dismissButton: {
      backgroundColor: '#404040',
    },
    notificationsContainer: {
      marginBottom: verticalScale(20),
    },
    optionsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginTop: verticalScale(10, 0.3),
      marginBottom: verticalScale(5, 0.3),
      paddingHorizontal: horizontalScale(5, 0.3),
      width: '100%',
    },
    optionCard: {
      backgroundColor: '#1a1a1a',
      borderRadius: 10,
      borderColor:'#ffffff',
      borderWidth: 1,
      padding: 10,
      width: '47%',
      marginRight: '0%',
      marginLeft: '2%',
      height: 180,
      marginBottom: 15,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      alignItems: 'center',
      justifyContent: 'center',
    },
    optionTitle: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#ffffff',
      marginTop: 5,
      textAlign: 'center',
      width: '100%',
    },
    optionDescription: {
      fontSize: 10,
      color: '#cccccc',
      marginTop: 2,
      textAlign: 'center',
      width: '100%',
    },
    requestRoleButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#ff4757',
      padding: moderateScale(10),
      borderRadius: moderateScale(20),
      marginTop: verticalScale(10),
    },
    requestRoleText: {
      color: '#ffffff',
      marginLeft: horizontalScale(5),
      fontSize: moderateScale(16),
      fontWeight: 'bold',
    },
  
  });