import { StyleSheet, Platform, StatusBar } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#000000',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  header: {
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: '#000000',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginBottom: 25,
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  welcomeContainer: {
    marginRight: 80,
    marginBottom: 10,
  },
  welcome: {
    fontSize: 26,
    color: '#ffffff',
    fontWeight: '400',
    lineHeight: 32,
  },
  userName: {
    fontSize: 34,
    color: '#FF3A5E',
    fontWeight: 'bold',
    marginTop: 5,
  },
  headerButton: {
    position: 'absolute',
    right: 20,
    top: 50,
    backgroundColor: '#865FF4',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 25,
    shadowColor: '#FF3A5E',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  headerButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  optionsContainer: {
    padding: 20,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  optionCard: {
    backgroundColor: '#1a1a1a',
    borderRadius: 18,
    borderColor:'#865FF4',
    borderWidth: 1,
    padding: 22,
    width: '47%',
    marginBottom: 20,
    elevation: 5,
    shadowColor: '#fff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#ffffff',
    marginTop: 12,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  optionDescription: {
    fontSize: 13,
    color: '#cccccc',
    marginTop: 6,
    textAlign: 'center',
    letterSpacing: 0.2,
  },
});