import { StyleSheet, Platform, StatusBar } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#000000',
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: {
      flex: 1,
      backgroundColor: '#121212',
      padding: 15,
      paddingTop: 35, // Margen para respetar la barra de estado
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      backgroundColor: '#1a1a1a',
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    modalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.95)',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 9999,
      paddingTop: 35, // Margen para respetar la barra de estado
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      backgroundColor: '#1a1a1a',
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#ffffff',
      marginRight: 10,
    },
    notificationBadge: {
      backgroundColor: '#FF3A5E',
      borderRadius: 15,
      minWidth: 30,
      height: 30,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 8,
      marginLeft: 10,
      borderWidth: 2,
      borderColor: '#FFFFFF',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 5,
    },
    notificationCount: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
    closeButton: {
      padding: 8,
    },
    notificationsList: {
      flex: 1,
    },
    noNotificationsText: {
      color: '#ffffff',
      textAlign: 'center',
      fontSize: 16,
      marginTop: 20,
    },
    container: {
      flex: 1,
      backgroundColor: '#000000',
    },
    header: {
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight + 10 : 50, // Ajustado dinámicamente para respetar la barra de estado
      paddingHorizontal: 20,
      paddingBottom: 15,
      backgroundColor: '#000000',
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      marginBottom: 20,
    },
    welcomeContainer: {
      marginRight: 50,
    },
    welcome: {
      fontSize: 24,
      color: '#ffffff',
      fontWeight: '300',
    },
    userName: {
      fontSize: 32,
      color: '#ffffff',
      fontWeight: 'bold',
    },
    headerButton: {
      position: 'absolute',
      right: 20,
      top: Platform.OS === 'android' ? StatusBar.currentHeight + 10 : 50, // Ajustado dinámicamente para alinearse con el header
      backgroundColor: '#ff4757',
      paddingHorizontal: 15,
      paddingVertical: 8,
      borderRadius: 20,
    },
    headerButtonText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '600',
    },
    notification: {
      backgroundColor: '#1a1a1a',
      borderRadius: 12,
      padding: 16,
      marginHorizontal: 20,
      marginBottom: 10,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    notificationText: {
      fontSize: 16,
      color: '#ffffff',
      marginBottom: 10,
    },
    notificationActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 10,
    },
    notificationButtonText: {
      color: '#ffffff',
      fontSize: 14,
      fontWeight: 'bold',
    },
    artistButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
    profileButtonsContainer: {
      marginTop: 16,
      marginBottom: 24,
      paddingHorizontal: 20,
    },
    profileSection: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    profileButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#865FF4',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderTopLeftRadius: 8,
      borderBottomLeftRadius: 8,
    },
    managerButton: {
      backgroundColor: '#00EA01',
    },
    deleteButton: {
      backgroundColor: '#E74C3C',
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderTopRightRadius: 8,
      borderBottomRightRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
    },
    deleteManagerButton: {
      backgroundColor: '#C0392B',
    },
    profileButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
      marginLeft: 10,
    },
    dismissButton: {
      backgroundColor: '#404040',
    },
    notificationsContainer: {
      marginBottom: 20,
    },
    optionsContainer: {
      padding: 20,
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    optionCard: {
      backgroundColor: '#1a1a1a',
      borderRadius: 15,
      borderColor:'#ffffff',
      borderWidth:1,
      padding: 20,
      width: '47%',
      marginBottom: 20,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      alignItems: 'center',
    },
    optionTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#ffffff',
      marginTop: 10,
      textAlign: 'center',
    },
    optionDescription: {
      fontSize: 12,
      color: '#cccccc',
      marginTop: 5,
      textAlign: 'center',
    },
    requestRoleButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#ff4757',
      padding: 10,
      borderRadius: 20,
      marginTop: 10,
    },
    requestRoleText: {
      color: '#ffffff',
      marginLeft: 5,
      fontSize: 16,
      fontWeight: 'bold',
    },
  
  });