import { StyleSheet, Platform, StatusBar } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#1A1A1A',
      paddingTop: 0,
      paddingBottom: 0,
    },
    header: {
      backgroundColor: '#1A1A1A',
      paddingVertical: 12,
      borderBottomWidth: 0,
      elevation: 0,
      shadowOpacity: 0,
    },
    headerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
    },
    backButton: {
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitle: {
      color: '#FFF',
      fontSize: 22,
      fontWeight: 'bold',
      textAlign: 'center',
      flex: 1,
    },
    headerRight: {
      width: 40,
      alignItems: 'flex-end',
    },
    searchContainer: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 16,
      backgroundColor: '#1A1A1A',
      alignItems: 'center',
      marginTop: 0,
    },
    searchInputWrapper: {
      flex: 1,
      flexDirection: 'row',
      backgroundColor: '#333',
      borderRadius: 25,
      paddingHorizontal: 16,
      paddingVertical: 12,
      alignItems: 'center',
      marginRight: 12,
    },
    searchIcon: {
      marginRight: 10,
    },
    searchInput: {
      flex: 1,
      color: '#FFF',
      fontSize: 16,
    },
    filterButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#333',
      justifyContent: 'center',
      alignItems: 'center',
    },
    filterButtonActive: {
      backgroundColor: '#FF3A5E',
    },
    categoriesContainer: {
      marginTop: 5,
      marginBottom: 15,
      maxHeight: 40,
    },
    categoriesContentContainer: {
      paddingHorizontal: 16,
      alignItems: 'center',
    },
    categoryChip: {
      backgroundColor: '#2C2C2C',
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 20,
      marginRight: 10,
      borderWidth: 1,
      borderColor: '#3E3E3E',
      height: 36,
      justifyContent: 'center',
    },
    selectedCategoryChip: {
      backgroundColor: '#FF3A5E',
      borderColor: '#FF3A5E',
    },
    categoryChipText: {
      color: '#FFF',
      fontSize: 14,
      fontWeight: '500',
    },
    selectedCategoryChipText: {
      color: '#FFF',
      fontWeight: 'bold',
    },
    appliedFiltersContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: '#222',
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    appliedFilterChip: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FF3A5E',
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 6,
      marginRight: 8,
      marginBottom: 8,
    },
    appliedFilterText: {
      color: '#FFF',
      fontSize: 12,
      marginRight: 4,
    },
    clearAllFiltersButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#333',
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 6,
      marginBottom: 8,
    },
    clearAllFiltersText: {
      color: '#FFF',
      fontSize: 12,
    },
    eventList: {
      flex: 1,
    },
    eventListContent: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 24,
    },
    loader: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    noEventsContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    noEventsTitle: {
      color: '#FFF',
      fontSize: 20,
      fontWeight: 'bold',
      marginTop: 16,
      marginBottom: 8,
    },
    noEventsText: {
      color: '#95A5A6',
      fontSize: 16,
      textAlign: 'center',
      maxWidth: '80%',
    },
    modalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: '#2C2C2C',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingBottom: 20,
      maxHeight: '80%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    modalTitle: {
      color: '#FFF',
      fontSize: 18,
      fontWeight: 'bold',
    },
    modalBody: {
      padding: 15,
    },
    dateFilterContainer: {
      marginBottom: 15,
    },
    dateDisplay: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    dateItem: {
      flex: 1,
      marginHorizontal: 5,
    },
    dateLabel: {
      color: '#FFF',
      fontSize: 14,
      marginBottom: 5,
    },
    dateButton: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: '#333',
      borderRadius: 8,
      padding: 10,
      borderWidth: 1,
      borderColor: '#444',
    },
    dateButtonText: {
      color: '#FFF',
      fontSize: 14,
    },
    calendarContainer: {
      backgroundColor: '#2C2C2C',
      borderRadius: 12,
      padding: 10,
      marginTop: 10,
    },
    calendarHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    calendarTitle: {
      color: '#FFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
    categoriesContentContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: 15,
    },
    filterLabel: {
      color: '#FFF',
      fontSize: 16,
      fontWeight: 'bold',
      marginTop: 16,
      marginBottom: 8,
    },
    calendar: {
      height: 300,
      borderRadius: 12,
      marginBottom: 16,
      backgroundColor: '#333',
    },
    locationsContainer: {
      marginBottom: 16,
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    locationChip: {
      backgroundColor: '#333',
      borderRadius: 25,
      paddingHorizontal: 16,
      paddingVertical: 10,
      marginRight: 8,
      marginBottom: 8,
      minWidth: 100,
      justifyContent: 'center',
      alignItems: 'center',
    },
    selectedLocationChip: {
      backgroundColor: '#FF3A5E',
    },
    locationChipText: {
      color: '#FFF',
      fontSize: 14,
      textAlign: 'center',
    },
    selectedLocationChipText: {
      color: '#FFF',
      fontWeight: 'bold',
    },
    modalFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 16,
      borderTopWidth: 1,
      borderTopColor: '#333',
    },
    clearButton: {
      backgroundColor: '#333',
      borderRadius: 25,
      padding: 12,
      flex: 1,
      marginRight: 8,
      alignItems: 'center',
    },
    clearButtonText: {
      color: '#FFF',
      fontSize: 16,
    },
    applyButton: {
      backgroundColor: '#FF3A5E',
      borderRadius: 25,
      padding: 12,
      flex: 1,
      marginLeft: 8,
      alignItems: 'center',
    },
    applyButtonText: {
      color: '#FFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
    eventCard: {
      backgroundColor: '#333',
      borderRadius: 12,
      padding: 16,
      marginHorizontal: 16,
      marginBottom: 12,
      position: 'relative',
      borderWidth: 2,
      borderColor: '#FF3A5E',
    },
    expiredEventCard: {
      borderColor: '#444',
      backgroundColor: '#2A2A2A',
    },
    eventCardContent: {
      flex: 1,
    },
    eventTitle: {
      color: '#FFFFFF',
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 12,
    },
    eventInfoContainer: {
      marginTop: 8,
    },
    eventInfoItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    eventInfoText: {
      color: '#FFFFFF',
      fontSize: 15,
      marginLeft: 10,
    },
    eventCategoryContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      position: 'absolute',
      top: 12,
      right: 12,
    },
    eventCategoryBadge: {
      backgroundColor: '#FF3A5E',
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 5,
    },
    eventCategoryBadgeText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: 'bold',
    },
    expiredEventBadge: {
      backgroundColor: '#666',
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 5,
    },
    expiredEventBadgeText: {
      color: '#FFFFFF',
      fontSize: 13,
    },
    favoriteButton: {
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
    },
    eventHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    eventTitle: {
      color: '#FFF',
      fontSize: 18,
      fontWeight: 'bold',
    },
    eventCategory: {
      backgroundColor: '#FF3A5E',
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    eventCategoryText: {
      color: '#FFF',
      fontSize: 12,
    },
    eventInfo: {
      marginTop: 16,
    },
    eventInfoItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    eventInfoText: {
      color: '#FFF',
      fontSize: 14,
      marginLeft: 8,
    },
    eventFooter: {
      marginTop: 16,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    emptyText: {
      color: '#FFF',
      fontSize: 16,
      textAlign: 'center',
    },
    eventsContainer: {
      flex: 1,
      backgroundColor: '#1A1A1A',
    },
    eventsListContent: {
      paddingTop: 5,
      paddingBottom: 20,
    },
    // Estilos para eventos expirados
    expiredEventCard: {
      opacity: 0.8,
      borderColor: '#D0D0D0',
    },
    expiredEventText: {
      color: '#A0A0A0',
    },
    expiredEventCategory: {
      backgroundColor: '#D0D0D0',
    },
    expiredEventCategoryText: {
      color: '#505050',
      fontSize: 12,
      fontWeight: 'bold',
    },
  });