import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS, SIZES } from './theme';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  header: {
    backgroundColor: '#000000',
    paddingTop: Platform.OS === 'ios' ? 60 : 35,
    paddingBottom: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    shadowColor: '#FF0000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 10,
    marginBottom: 20,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  titleContainer: {
    flex: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    letterSpacing: 0.5,
    textShadowColor: '#FF0000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    marginLeft: 20,
  },
  headerButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 140,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  headerButtonText: {
    color: '#FFF',
    fontWeight: '600',
    fontSize: 16,
    textAlign: 'center',
  },
  section: {
    padding: 20,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 15,
    letterSpacing: 0.5,
  },
  cardScroll: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  card: {
    width: width * 0.85,
    marginRight: 15,
    backgroundColor: '#000000',
    borderRadius: 20,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#FF0000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  cardImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
  },
  cardContent: {
    padding: 20,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  cardSubtitle: {
    fontSize: 16,
    color: COLORS.primary,
    marginBottom: 12,
  },
  cardDescription: {
    fontSize: 15,
    color: '#FFFFFF',
    lineHeight: 22,
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 15,
    padding: 20,
  },
  categoryCard: {
    flex: 1,
    minWidth: width * 0.4,
    aspectRatio: 1,
    backgroundColor: '#000000',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#FF0000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  categoryIcon: {
    marginBottom: 12,
  },
  categoryText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: SIZES.padding.sm,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: SIZES.padding.xs,
  },
  activeTabButton: {
    borderBottomWidth: 2,
    borderBottomColor: COLORS.primary,
  },
  tabButtonText: {
    fontSize: SIZES.caption,
    color: COLORS.text.secondary,
    marginTop: 4,
  },
  activeTabButtonText: {
    color: COLORS.primary,
  },
  content: {
    flex: 1,
  },
  eventCard: {
    width: width * 0.8,
    height: 200,
    marginRight: SIZES.margin.md,
    borderRadius: SIZES.radius.lg,
    backgroundColor: COLORS.surface,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  eventCardContent: {
    flex: 1,
    padding: SIZES.padding.md,
    justifyContent: 'space-between',
  },
  eventTitle: {
    fontSize: SIZES.h2,
    fontWeight: 'bold',
    color: COLORS.text.primary,
  },
  eventDate: {
    fontSize: SIZES.body,
    color: COLORS.primary,
  },
  eventDescription: {
    fontSize: SIZES.body,
    color: COLORS.text.secondary,
  },
  artistCard: {
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius.md,
    marginBottom: SIZES.margin.md,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  artistCardContent: {
    padding: SIZES.padding.md,
  },
  artistName: {
    fontSize: SIZES.h3,
    fontWeight: 'bold',
    color: COLORS.text.primary,
    marginBottom: SIZES.margin.xs,
  },
  artistSpecialty: {
    fontSize: SIZES.body,
    color: COLORS.primary,
    marginBottom: SIZES.margin.xs,
  },
  artistDescription: {
    fontSize: SIZES.body,
    color: COLORS.text.secondary,
  },
  spaceCard: {
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius.md,
    marginBottom: SIZES.margin.md,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  spaceCardContent: {
    padding: SIZES.padding.md,
  },
  spaceName: {
    fontSize: SIZES.h3,
    fontWeight: 'bold',
    color: COLORS.text.primary,
    marginBottom: SIZES.margin.xs,
  },
  spaceType: {
    fontSize: SIZES.body,
    color: COLORS.primary,
    marginBottom: SIZES.margin.xs,
  },
  spaceDescription: {
    fontSize: SIZES.body,
    color: COLORS.text.secondary,
  },
  fab: {
    position: 'absolute',
    right: SIZES.margin.lg,
    bottom: SIZES.margin.lg,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  snackbar: {
    position: 'absolute',
    bottom: SIZES.margin.xl,
    left: SIZES.margin.lg,
    right: SIZES.margin.lg,
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius.md,
    padding: SIZES.padding.md,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  snackbarText: {
    color: COLORS.text.primary,
    fontSize: SIZES.body,
    textAlign: 'center',
  },
  viewAllButton: {
    backgroundColor: COLORS.surface,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    marginHorizontal: 20,
  },
  viewAllText: {
    color: COLORS.primary,
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  continueButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    paddingHorizontal: 25,
    borderRadius: 25,
    marginTop: 10,
    borderWidth: 2,
    borderColor: '#FF0000',
  },
});
