import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS, SIZES } from './theme';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#000000',
  },
  scrollContainer: {
    flex: 1,
    backgroundColor: '#000000',
  },
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  header: {
    backgroundColor: '#000000',
    paddingTop: 15, // Reducido porque ya estamos usando SafeAreaView con paddingTop
    paddingBottom: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    shadowColor: '#FF0000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 10,
    marginBottom: 20,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  titleContainer: {
    flex: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    letterSpacing: 0.5,
    textShadowColor: '#FF0000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    marginLeft: 20,
  },
  headerButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 140,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  headerButtonText: {
    color: '#FFF',
    fontWeight: '600',
    fontSize: 16,
    textAlign: 'center',
  },
  viewAllText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
  section: {
    padding: 20,
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 15,
    letterSpacing: 0.5,
  },
  cardScroll: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  loadingContainer: {
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#121212',
    borderRadius: 15,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  errorText: {
    color: '#FF3A5E',
    fontSize: 16,
    textAlign: 'center',
    padding: 20,
  },
  emptyText: {
    color: '#AAAAAA',
    fontSize: 16,
    textAlign: 'center',
    padding: 20,
  },
  card: {
    width: width * 0.85,
    marginRight: 15,
    backgroundColor: '#000000',
    borderRadius: 20,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#FF0000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  cardImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
  },
  cardContent: {
    padding: 20,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  cardSubtitle: {
    fontSize: 16,
    color: COLORS.primary,
    marginBottom: 12,
  },
  cardDescription: {
    fontSize: 15,
    color: '#FFFFFF',
    lineHeight: 22,
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 15,
    padding: 20,
  },
  categoryCard: {
    flex: 1,
    minWidth: width * 0.4,
    aspectRatio: 1,
    backgroundColor: '#000000',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#FF0000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  categoryIcon: {
    marginBottom: 12,
  },
  categoryText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: SIZES.padding.sm,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: SIZES.padding.xs,
  },
  activeTabButton: {
    borderBottomWidth: 2,
    borderBottomColor: COLORS.primary,
  },
  tabButtonText: {
    fontSize: SIZES.caption,
    color: COLORS.text.secondary,
    marginTop: 4,
  },
  activeTabButtonText: {
    color: COLORS.primary,
  },
  content: {
    flex: 1,
  },
  eventCard: {
    width: width * 0.8,
    height: 200,
    marginRight: SIZES.margin.md,
    borderRadius: SIZES.radius.lg,
    backgroundColor: COLORS.surface,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  eventCardContent: {
    flex: 1,
    padding: SIZES.padding.md,
    justifyContent: 'space-between',
  },
  eventTitle: {
    fontSize: SIZES.h2,
    fontWeight: 'bold',
    color: COLORS.text.primary,
  },
  eventDate: {
    fontSize: SIZES.body,
    color: COLORS.primary,
  },
  eventDescription: {
    fontSize: SIZES.body,
    color: COLORS.text.secondary,
  },
  artistCard: {
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius.md,
    marginBottom: SIZES.margin.md,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  artistCardContent: {
    padding: SIZES.padding.md,
  },
  artistName: {
    fontSize: SIZES.h3,
    fontWeight: 'bold',
    color: COLORS.text.primary,
    marginBottom: SIZES.margin.xs,
  },
  artistSpecialty: {
    fontSize: SIZES.body,
    color: COLORS.primary,
    marginBottom: SIZES.margin.xs,
  },
  artistDescription: {
    fontSize: SIZES.body,
    color: COLORS.text.secondary,
  },
  spaceCard: {
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius.md,
    marginBottom: SIZES.margin.md,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  spaceCardContent: {
    padding: SIZES.padding.md,
  },
  spaceName: {
    fontSize: SIZES.h3,
    fontWeight: 'bold',
    color: COLORS.text.primary,
    marginBottom: SIZES.margin.xs,
  },
  spaceType: {
    fontSize: SIZES.body,
    color: COLORS.primary,
    marginBottom: SIZES.margin.xs,
  },
  spaceDescription: {
    fontSize: SIZES.body,
    color: COLORS.text.secondary,
  },
  fab: {
    position: 'absolute',
    right: SIZES.margin.lg,
    bottom: SIZES.margin.lg,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  snackbar: {
    position: 'absolute',
    bottom: SIZES.margin.xl,
    left: SIZES.margin.lg,
    right: SIZES.margin.lg,
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius.md,
    padding: SIZES.padding.md,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  snackbarText: {
    color: COLORS.text.primary,
    fontSize: SIZES.body,
    textAlign: 'center',
  },
  viewAllButton: {
    backgroundColor: COLORS.surface,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    marginHorizontal: 20,
  },
  viewAllText: {
    color: COLORS.primary,
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  continueButton: {
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    paddingHorizontal: 25,
    borderRadius: 25,
    marginTop: 10,
    borderWidth: 2,
    borderColor: '#FF0000',
  },
  
  // Estilos para la sección de conexión cultural
  culturalHeroSection: {
    marginBottom: 25,
    borderRadius: 20,
    overflow: 'hidden',
    marginHorizontal: 15,
    elevation: 10,
    shadowColor: '#FF3A5E',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  culturalHeroBackground: {
    width: '100%',
    height: 380,
    backgroundColor: '#000000',
    justifyContent: 'flex-end',
  },
  culturalHeroContent: {
    padding: 20,
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  culturalHeroTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
    textShadowColor: '#FF3A5E',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  culturalHeroSubtitle: {
    fontSize: 18,
    color: '#FFFFFF',
    marginBottom: 15,
    opacity: 0.9,
  },
  culturalHeroDescription: {
    fontSize: 16,
    color: '#FFFFFF',
    marginBottom: 20,
    opacity: 0.8,
    lineHeight: 22,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
    marginBottom: 10,
  },
  statItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  statIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FF3A5E',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  statCount: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 14,
    color: '#FFFFFF',
    opacity: 0.8,
  },
  
  // Estilos para la sección de destacados
  featuredSection: {
    padding: 20,
    marginBottom: 25,
  },
  featuredContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 20,
  },
  featuredCard: {
    width: width * 0.38,
    height: 180,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: '#000000',
    elevation: 5,
    shadowColor: '#FF3A5E',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  featuredImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  featuredOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 10,
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  featuredIconContainer: {
    position: 'absolute',
    top: -20,
    left: 10,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FF3A5E',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  featuredTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 5,
  },
  featuredSubtitle: {
    fontSize: 12,
    color: '#FFFFFF',
    opacity: 0.8,
  },
  connectionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: width * 0.14,
  },
  connectionLine: {
    flex: 1,
    height: 2,
    backgroundColor: '#FF3A5E',
  },
  connectionCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FF3A5E',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 5,
  },
  connectionText: {
    fontSize: 14,
    color: '#FFFFFF',
    opacity: 0.8,
    textAlign: 'center',
    marginVertical: 15,
    fontStyle: 'italic',
  },
  exploreButton: {
    backgroundColor: '#FF3A5E',
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 10,
    shadowColor: '#FF3A5E',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  exploreButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
    marginRight: 8,
  },
  
  // Estilo para la sección del calendario
  calendarSection: {
    padding: 20,
    marginBottom: 15,
    backgroundColor: '#121212',
    borderRadius: 15,
    marginHorizontal: 15,
    shadowColor: '#FF3A5E',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  calendarWrapper: {
    height: 600, // Altura fija para el calendario
    overflow: 'hidden',
    borderRadius: 10,
  },
  calendarContainer: {
    backgroundColor: '#121212',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 15,
    paddingBottom: 0,
    marginTop: 15,
    shadowColor: '#FF3A5E',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  calendarTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 15,
    textAlign: 'center',
  },
  // Estilos para la sección del calendario
  calendarSection: {
    marginTop: 20,
    marginBottom: 30,
    paddingHorizontal: 15,
  },
  calendarWrapper: {
    backgroundColor: '#111111',
    borderRadius: 12,
    padding: 10,
    paddingHorizontal: 5,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  calendarContainer: {
    width: '100%',
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    paddingHorizontal: 5,
  },
  calendarTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  eventItem: {
    marginVertical: 8,
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#FF3A5E',
    backgroundColor: '#222222',
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  eventName: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#FFFFFF',
    flex: 1,
  },
  eventBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: '#FF3A5E66',
  },
  eventBadgeText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  eventDescription: {
    color: '#CCCCCC',
    marginBottom: 8,
  },
  eventDetails: {
    marginTop: 5,
    backgroundColor: '#333333',
    borderRadius: 6,
    padding: 8,
  },
  eventDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
    marginBottom: 3,
  },
  eventDetailText: {
    fontSize: 13,
    color: '#DDDDDD',
    marginLeft: 8,
  },
  viewMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
    paddingVertical: 10,
  },
  viewMoreText: {
    color: '#FF3A5E',
    fontWeight: '600',
    marginRight: 5,
  },
  
  // Estilos para el banner de invitación a iniciar sesión
  loginBanner: {
    marginTop: 20,
    marginBottom: 30,
    marginHorizontal: 15,
    backgroundColor: '#1E1E1E',
    borderRadius: 12,
    padding: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#FF3A5E',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  loginBannerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 10,
  },
  loginBannerText: {
    fontSize: 14,
    color: '#CCCCCC',
    marginBottom: 15,
    lineHeight: 20,
  },
  loginBannerButton: {
    backgroundColor: '#FF3A5E',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginBannerButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 15,
    marginRight: 8,
  },
});
