import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#000000',
    },
    listContent: {
      padding: 16,
    },
    notificationItem: {
      backgroundColor: '#1E1E1E',
      borderRadius: 12,
      marginBottom: 12,
      overflow: 'hidden',
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      borderWidth: 1,
      borderColor: '#2A2A2A',
    },
    readNotification: {
      backgroundColor: '#141414',
      opacity: 0.85,
      borderColor: '#1A1A1A',
    },
    notificationContent: {
      padding: 16,
    },
    notificationHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    title: {
      fontSize: 17,
      fontWeight: '600',
      color: '#E0E0E0',
      flex: 1,
      letterSpacing: 0.3,
    },
    readTitle: {
      color: '#808080',
      fontWeight: '500',
    },
    message: {
      fontSize: 15,
      color: '#CCCCCC',
      marginBottom: 16,
      lineHeight: 22,
      letterSpacing: 0.2,
    },
    readMessage: {
      color: '#666666',
    },
    unreadDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#3B82F6',
      marginLeft: 8,
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 4,
    },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: 12,
      gap: 8,
      flexWrap: 'wrap',
    },
    deleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 8,
      minWidth: 90,
      justifyContent: 'center',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    actionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 8,
      minWidth: 90,
      justifyContent: 'center',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    buttonText: {
      color: '#FFFFFF',
      fontSize: 13.5,
      fontWeight: '600',
      marginLeft: 6,
      letterSpacing: 0.2,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
      marginTop: 50,
    },
    emptyText: {
      textAlign: 'center',
      color: '#808080',
      fontSize: 16,
      marginTop: 16,
      letterSpacing: 0.3,
    },
  });
  