import { StyleSheet } from 'react-native';
;

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#1A1A1A', // Fondo oscuro
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 25,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  roleSelector: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 35,
  },
  roleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ff4757',
    width: '48%',
    backgroundColor: 'rgba(255, 71, 87, 0.1)', // Fondo semi-transparente
  },
  roleButtonSelected: {
    backgroundColor: '#ff4757',
    shadowColor: '#ff4757',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  roleButtonText: {
    marginLeft: 10,
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  roleButtonTextSelected: {
    color: '#FFF',
  },
  fieldTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
    marginTop: 15,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  input: {
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 8,
    padding: 15,
    marginBottom: 15,
    fontSize: 17,
    backgroundColor: '#F8F9FA',
  },
  inputError: {
    borderColor: '#FF4757',
    borderWidth: 2,
    backgroundColor: 'rgba(255, 71, 87, 0.1)',
  },
  errorText: {
    color: '#FF4757',
    fontSize: 14,
    marginTop: -14,
    marginBottom: 14,
    marginLeft: 4,
  },
  textArea: {
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 8,
    padding: 15,
    marginBottom: 15,
    fontSize: 17,
    minHeight: 100,
    textAlignVertical: 'top',
    backgroundColor: '#F8F9FA',
  },
  textAreaError: {
    borderColor: '#FF4757',
    borderWidth: 2,
    backgroundColor: 'rgba(255, 71, 87, 0.1)',
  },
  portfolioContainer: {
    marginBottom: 20,
  },
  portfolioInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  portfolioInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#333333',
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    backgroundColor: '#2A2A2A',
    color: '#FFFFFF',
  },
  addLinkButton: {
    marginLeft: 12,
    padding: 8,
    backgroundColor: '#4A90E2',
    borderRadius: 8,
  },
  portfolioItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#333333',
  },
  portfolioLink: {
    flex: 1,
    marginRight: 12,
    color: '#FFFFFF',
  },
  documentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#4A90E2',
    borderRadius: 15,
    marginTop: 25,
    backgroundColor: 'rgba(74, 144, 226, 0.1)',
  },
  documentButtonText: {
    marginLeft: 12,
    fontSize: 16,
    color: '#4A90E2',
    fontWeight: '500',
  },
  documentsList: {
    marginTop: 15,
  },
  documentsTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  documentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#333333',
  },
  documentName: {
    flex: 1,
    marginLeft: 12,
    marginRight: 12,
    fontSize: 15,
    color: '#FFFFFF',
  },
  removeDocumentButton: {
    padding: 6,
    backgroundColor: 'rgba(255, 107, 107, 0.2)',
    borderRadius: 8,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 35,
    marginBottom: 25,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 12,
    width: '45%',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    height: 50,
  },
  submitButton: {
    backgroundColor: '#4A90E2',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  cancelButton: {
    backgroundColor: '#FF6B6B',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: 'bold',
    textAlign: 'center',
    width: '100%',
    letterSpacing: 0.5,
  },
});
